{"uuid": "d571a18f-7562-45ca-821b-0e8807308284", "children": ["c226c02b-ab3d-470b-b387-4b4f99df452f"], "befores": [{"name": "driver", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.SessionNotCreatedException: Message: Could not create a session: The Safari instance terminated while trying to pair with it.\n\n", "trace": "  File \"/Users/chethangopal/Desktop/SwagSuace/.venv/lib/python3.11/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/Users/chethangopal/Desktop/SwagSuace/.venv/lib/python3.11/site-packages/_pytest/setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"/Users/chethangopal/Desktop/SwagSuace/.venv/lib/python3.11/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/chethangopal/Desktop/SwagSuace/.venv/lib/python3.11/site-packages/_pytest/fixtures.py\", line 1122, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/chethangopal/Desktop/SwagSuace/.venv/lib/python3.11/site-packages/_pytest/fixtures.py\", line 877, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"/Users/chethangopal/Desktop/SwagSuace/Tests/conftest.py\", line 27, in driver\n    driver = webdriver.Safari()\n             ^^^^^^^^^^^^^^^^^^\n  File \"/Users/chethangopal/Desktop/SwagSuace/.venv/lib/python3.11/site-packages/selenium/webdriver/safari/webdriver.py\", line 60, in __init__\n    super().__init__(command_executor=executor, options=options)\n  File \"/Users/chethangopal/Desktop/SwagSuace/.venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 208, in __init__\n    self.start_session(capabilities)\n  File \"/Users/chethangopal/Desktop/SwagSuace/.venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 292, in start_session\n    response = self.execute(Command.NEW_SESSION, caps)[\"value\"]\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/chethangopal/Desktop/SwagSuace/.venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 347, in execute\n    self.error_handler.check_response(response)\n  File \"/Users/chethangopal/Desktop/SwagSuace/.venv/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1717189600563, "stop": 1717189602224}], "start": 1717189600563, "stop": 1717189602301}